version: '3'

services:
  app_db:
    build: ./
    command: ./forum
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    environment:
      DB_URL:  "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
      DB_PASSWORD: "postgres"
      JWT_SECRET: "secret"
    networks:
      - app-network

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./storage/postgres/migrations:/migrations
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network: